// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health": {
            "get": {
                "description": "Zeigt an, ob der Proxy läuft, und gibt die aktuelle Version aus.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health-Check abrufen",
                "responses": {
                    "200": {
                        "description": "Erfolgreiche Antwort",
                        "schema": {
                            "$ref": "#/definitions/web.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/stats": {
            "get": {
                "description": "Gibt die Anzahl der aktuell in BadgerDB zwischengespeicherten Nachrichten zurück.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Puffer-Statistik abrufen",
                "responses": {
                    "200": {
                        "description": "Erfolgreiche Antwort",
                        "schema": {
                            "$ref": "#/definitions/web.StatsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "web.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status der Anwendung (normalerweise \"ok\").",
                    "type": "string"
                },
                "version": {
                    "description": "Die aktuelle Version der Proxy-Anwendung.",
                    "type": "string"
                }
            }
        },
        "web.StatsResponse": {
            "type": "object",
            "properties": {
                "buffer_count": {
                    "description": "Die aktuelle Anzahl der in BadgerDB zwischengespeicherten Nachrichten.",
                    "type": "integer"
                },
                "messages_forward_failed_total": {
                    "type": "integer"
                },
                "messages_forwarded_total": {
                    "type": "integer"
                },
                "messages_received_total": {
                    "type": "integer"
                },
                "messages_stored_total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
